### ISSUE TITLE
JHWV 密集遮挡道路数据集

### ISSUE THREAD

**Issue by chl916185** [WanderRainy/OARENet#1]
大佬，JHWV 密集遮挡道路数据集怎么下载啊
@WanderRainy

**Comment by WanderRainy** [comment]
十分抱歉，目前还没有开源数据的计划。一是因为这个数据是在项目里单独购买的。二是目前针对这个数据集还有进一步的研究计划。

**Comment by chl916185** [comment]
> 十分抱歉，目前还没有开源数据的计划。一是因为这个数据是在项目里单独购买的。二是目前针对这个数据集还有进一步的研究计划。

好的，谢谢您的解答。
