### ISSUE TITLE
权重文件获取

### ISSUE THREAD

**Issue by niuma345** [WanderRainy/OARENet#2]
您好，在复现您的代码的时候
class BAM_LinkNet50(nn.Module):
    def __init__(self, num_classes=1):
        super(BAM_LinkNet50, self).__init__()

        filters = [256, 512, 1024, 2048]
        resnet = res2net50(pretrained=True)
        # # resnet1 = ResidualNet('ImageNet', 50, 1000, att_type='BAM', path='/home/lxy/new_experiments/prelogs/RESNET50_IMAGENET_BAM_best.pth.tar')
        resnet1 = ResidualNet('ImageNet', 50, 1000, att_type='BAM',
                              path=r'./prelogs/RESNET50_IMAGENET_BAM_best.pth.tar')
这一部分代码FileNotFoundError: Checkpoint file not found at './prelogs/RESNET50_IMAGENET_BAM_best.pth.tar'，请问一下这个文件在哪可以下载，期待大佬的回复

**Comment by WanderRainy** [comment]
sorry, i just saw this issue, this is the shared link https://drive.google.com/file/d/1b8T4apEQGulTrmoYsjynIynIatvaFgGe/view?usp=sharing.

**Comment by niuma345** [comment]
> sorry, i just saw this issue, this is the shared link https://drive.google.com/file/d/1b8T4apEQGulTrmoYsjynIynIatvaFgGe/view?usp=sharing.

非常感谢您的回复，我的问题得到了解决，感谢大佬

**Comment by HEIXIUUU** [comment]
> > sorry, i just saw this issue, this is the shared link https://drive.google.com/file/d/1b8T4apEQGulTrmoYsjynIynIatvaFgGe/view?usp=sharing.
> 
> 非常感谢您的回复，我的问题得到了解决，感谢大佬

您好，请问您下载下来的权重文件压缩包是怎么使用的？

**Comment by WanderRainy** [comment]
模型文件中有加载这个权重文件的参数
