### ISSUE TITLE
resources of pre-trained weighted

### ISSUE THREAD

**Issue by HEIXIUUU** [WanderRainy/OARENet#3]
Hello, can you update this pretrained weight as it cannot be extracted?

**Comment by WanderRainy** [comment]
.pth.tar is a weighted file, which don't need to extracted

**Comment by HEIXIUUU** [comment]
> .pth.tar is a weighted file, which don't need to extracted

Just need to put the zip file in the home directory to use it?

**Comment by WanderRainy** [comment]
yeah，

**Comment by HEIXIUUU** [comment]
> yeah，

If I want to achieve road segmentation extraction, does OARENet need to be used together with the other encoders mentioned in the paper, or can it be used alone?

**Comment by WanderRainy** [comment]
other encoders，its a decoder

**Comment by HEIXIUUU** [comment]
> other encoders，its a decoder

ok, I get it. 3q
