### ISSUE TITLE
Hello, I would like to ask, for the same model, how many times did you run it to get the results? Did you take the highest value or the average?

### ISSUE THREAD

**Issue by malatang20001210** [WanderRainy/OARENet#5]

**Comment by WanderRainy** [comment]
just one, I fixed the random numbers to ensure that they can be accurately reproduced on the same device.

**Comment by malatang20001210** [comment]
But can the results be consistent every time without setting seeds for the DataLoader num_workers?

**Comment by WanderRainy** [comment]
Must be different. I have not calculated the mean and variance of the results under this experimental condition.

**Comment by malatang20001210** [comment]
So your model should also produce different results each time, but the difference is not significant because you set the seed, and you only took the result of one run. I don’t mean anything else by this; I’m just encountering an issue where the results vary each time. Thank you so much for replying to me so quickly!

**Comment by WanderRainy** [comment]
right

**Comment by malatang20001210** [comment]
Thank you so much! Best wishes!
